DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS car_client;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS rental;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS car;



CREATE TABLE users
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logins           VARCHAR(50) NOT NULL,
    email            VARCHAR(20) NOT NULL UNIQUE,
    phone            VARCHAR(30) NOT NULL UNIQUE,
    passwords        VARCHAR(20) NOT NULL,
    roles            VARCHAR(7)  NOT NULL,
    date_of_creation TIMESTAMP   NOT NULL
);

CREATE TABLE car
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand            VARCHAR(20)      NOT NULL,
    model            VARCHAR(20)      NOT NULL,
    year_of_release  INT              NOT NULL CHECK (year_of_release > 2000),
    color            VARCHAR(20)      NOT NULL,
    fuel             VARCHAR(20)      NOT NULL,
    engine_capacity  DOUBLE PRECISION NOT NULL CHECK (engine_capacity > 0.0),
    horse_power      INT              NOT NULL CHECK (horse_power > 0),
    transmission     VARCHAR(20)      NOT NULL,
    fuel_consumption DOUBLE PRECISION NULL CHECK (fuel_consumption > 0.0),
    ranges           INT              NULL,
    battery          DOUBLE PRECISION NULL,
    car_type         VARCHAR(20)      NOT NULL,
    quantity_places  INT              NOT NULL CHECK (quantity_places > 0),
    quantity_doors   INT              NOT NULL CHECK (quantity_doors > 0),
    trunk_volume     INT              NOT NULL CHECK (trunk_volume > 0),
    vin_code         VARCHAR(20)      NOT NULL UNIQUE,
    numbers          VARCHAR(20)      NOT NULL UNIQUE,
    price            DOUBLE PRECISION NOT NULL CHECK ( price > 0 )
);


CREATE TABLE client
(
    id               INT PRIMARY KEY REFERENCES client (id) ON DELETE CASCADE,
    first_name       VARCHAR(20)  NOT NULL,
    last_name        VARCHAR(20)  NOT NULL,
    phone            VARCHAR(30)  NOT NULL UNIQUE,
    address          VARCHAR(100) NULL,
    date_of_birthday DATE         NOT NULL,
    date_of_creation TIMESTAMP    NOT NULL
);

CREATE TABLE documents
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id         INT        NOT NULL UNIQUE REFERENCES client (id) ON DELETE CASCADE,
    passport_serial   VARCHAR(2) NOT NULL,
    passport_No       INT        NOT NULL UNIQUE,
    driver_license_No VARCHAR(9) NOT NULL UNIQUE,
    date_of_creation  TIMESTAMP  NOT NULL
);

CREATE TABLE rental
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id           INT              NOT NULL REFERENCES car (id) ON DELETE CASCADE,
    client_id        INT              NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    rental_date      DATE             NOT NULL,
    return_date      DATE             NOT NULL,
    price            DOUBLE PRECISION NOT NULL CHECK ( price > 0 ),
    rental_days      INTEGER          NOT NULL CHECK ( rental_days > 0 ),
    status           VARCHAR(10)      NOT NULL,
    date_of_creation TIMESTAMP        NOT NULL
);



CREATE TABLE car_client
(
    car_id    INT REFERENCES car (id),
    client_id INT REFERENCES client (id),
    PRIMARY KEY (car_id, client_id)
);

INSERT INTO users (logins, email, phone, passwords, roles, date_of_creation)
values ('admin', 'admin@mail.ru', '+375447876655', 'password', 'ADMIN', '2023-05-25');

INSERT INTO car
(color, quantity_doors, numbers, quantity_places, trunk_volume, vin_code, brand, engine_capacity,
 fuel_consumption, car_type, fuel, horse_power, transmission, model, price, year_of_release)
VALUES ('WHITE', 5, '1092873', 5, 587, '123-0948098j882d', 'Audy', 1.5, 7, 'no_electric', 'DIESEL', 125, 'AUTOMATIC',
        'A8', 102, 2020);

INSERT INTO car
(color, quantity_doors, numbers, quantity_places, trunk_volume, vin_code, brand, engine_capacity,
 ranges, battery, car_type, fuel, horse_power, transmission, model, price, year_of_release)
VALUES ('WHITE', 5, '1876786', 5, 580, '123-0945656876', 'BMW', 1.5, 500, 100, 'electric', 'ELECTRIC', 125, 'AUTOMATIC',
        'A8', 102, 2020);

INSERT INTO client (id, first_name, last_name, phone, address, date_of_birthday,
                    date_of_creation)
VALUES (1, 'Ivan', 'Potapenko', '+375447899840', 'Gomel,Mazurova,20', '1986-05-02',
        '2023-05-02');

INSERT INTO rental (car_id, client_id, rental_date, return_date, price, rental_days, status, date_of_creation)
VALUES (1, 1, '2023-05-20', '2023-05-23', 100, 3, 'CHECK', '2023-05-20');

INSERT INTO documents(client_id, passport_serial, passport_No, driver_license_No, date_of_creation)
VALUES (1, 'HB', '1209838', 'PAO123986', '2023-05-20');

INSERT INTO car_client (car_id, client_id)
VALUES (1, 1);